### ISSUE TITLE
支持 OSS 图片服务读取

### ISSUE THREAD

**Issue by zensh** [aliyun/oss-nodejs-sdk#9]
我在这个库里手改尝试了一下，一直是 403 错误哎

**Comment by fengmk2** [comment]
赞啊，可以先看看流程，目前我们先写文档 https://github.com/ali-sdk/ali-sdk/wiki#work-flow ，然后写实现代码。 @zensh 我给你的gmail邮箱查看密钥吧。

**Comment by fengmk2** [comment]
@zensh 你的邮箱是 admin@zensh.com 不支持 sharelock，能否给我你的 twitter 账号？

**Comment by zensh** [comment]
这么高级，https://twitter.com/izensh

**Comment by fengmk2** [comment]
@zensh ok了，通过 twitter 登录就能看的密钥了 https://sharelock.io/1/UiXOnkft-ARsfymJDAXqTq7Ta14dDSXYLedckxVrm_8.aAwq2t/6wh3kNVe-oyHvE0Xx5vmQTcTEmXdB3N9EoThqwSEJUjVfhk2dN/G7pWOrLXjniAoSbux6dKr_4mVnEaY06I5H6U0qQrWRVUPaDWcK/fIilpclv-4pSHFlCQfeJQpco3FnPCp_LVLa_eHzqohVTDzRpf3/j1Ep87L2k4MVXPSqJNFsTN8powW6me6bC2l1A-iU2pUZFLcG5u/kRDu1KHmjBEuWv9Wq-87VbNDktq7euPUDtoG9GHuwF0wNpPprQ/L8r6VWEkx7dbe3Get5H8cC1I6e_xW-P128fMonL4EVeEoWw-Q8/yIpWuIjZsrPp1Hn27oH3RcZfOPWpYPr-0l10xxSEYaDCfpWujs/KwWRuASwFkM17pYKhTL9pE1qWBXl6bqEuY0WthTVqwflM99wA0/C5oV1lso_hUSCAvcJUCvBeYws743Cues9zhvTcUfHBFD_nqgPL/hk_GwWUMhNiiQep3b6LnOi5fi6TQbZLZtiBIrxQGS5uNeta6kz/uu34lVzZX3F2vPUywYuWOTLUUMQCgRdv55VKPZ4dQ7boR-hWfQ/AkWBLSPpunVHCHx23rOif5D1tYzrb7v5B_kYiTfzJPd02ThTDT/VvbJjJpHfMQdbUoNXHgal80t6DLTkO295Ic7YbehW3ZJ5txLVd/lX2ual9PohlTw1HHriVnQ3QB4OVq1IZTYpSU8CXYSV0CfFCNS_/RpaCHqgYJ1Zmi0RcCtznE0vrUOYF-mj-wBk-t30qSe-Dm2lsLj/3dJJkQi9tMLLgS0Fdc1t9CFWvN-ovgGy2lgkdL_VnTrGUGj0si/Ey-_CuEeOyHr8qHRTeYIGqBNNhUpCL.zlnekbL7vC7bN6NrsH7/Ilw

**Comment by fengmk2** [comment]
也给你发了 @ali-sdk/owners 的邀请

**Comment by zensh** [comment]
都收到

**Comment by zensh** [comment]
https://github.com/ali-sdk/ali-oss/pull/10
